### ISSUE TITLE
Should the lines in test.FAT parse as floats? 

### ISSUE THREAD

**Issue by Scott3142** [Exodus032/Phone-Verification#3]
I seem to get floats (I think they're floats anyway - they have a .0 at the end of them) in the test.FAT file. I'm not sure if that is intentional or not? 

![image](https://user-images.githubusercontent.com/17796109/194299975-a561ce49-17b1-4973-ba7b-2ebba5674735.png)

**Comment by Exodus032** [comment]
intentional, when the timeblock is added onto the code to make sure that the code is entered within 30s it is made a float but converted to a str
